// players.js
const players = [
    { name: 'Pelé', points: 50, position: 'Forward' },
{ name: 'Diego Maradona', points: 50, position: 'Forward/Midfielder' },
{ name: 'Lionel Messi', points: 50, position: 'Forward/Winger' },
{ name: 'Cristiano Ronaldo', points: 50, position: 'Forward/Winger' },
{ name: 'Johan Cruyff', points: 45, position: 'Forward/Midfielder' },
{ name: 'Zinedine Zidane', points: 45, position: 'Midfielder' },
{ name: 'Ronaldo Nazário', points: 45, position: 'Forward' },
{ name: 'Franz Beckenbauer', points: 45, position: 'Defender/Midfielder' },
{ name: 'Michel Platini', points: 40, position: 'Midfielder' },
{ name: 'Alfredo Di Stéfano', points: 40, position: 'Forward/Midfielder' },
{ name: 'Ferenc Puskás', points: 40, position: 'Forward' },
{ name: 'Gerd Müller', points: 40, position: 'Forward' },
{ name: 'George Best', points: 35, position: 'Forward/Winger' },
{ name: 'Marco van Basten', points: 35, position: 'Forward' },
{ name: 'Eusébio', points: 35, position: 'Forward' },
{ name: 'Roberto Baggio', points: 35, position: 'Forward' },
{ name: 'Ronaldinho', points: 30, position: 'Midfielder/Forward' },
{ name: 'Thierry Henry', points: 30, position: 'Forward/Winger' },
{ name: 'Lothar Matthäus', points: 30, position: 'Midfielder' },
{ name: 'Paolo Maldini', points: 30, position: 'Defender' },
{ name: 'Xavi Hernández', points: 25, position: 'Midfielder' },
{ name: 'Andrés Iniesta', points: 25, position: 'Midfielder' },
{ name: 'Romário', points: 25, position: 'Forward' },
{ name: 'Ruud Gullit', points: 25, position: 'Midfielder/Forward' },
{ name: 'Gabriel Batistuta', points: 25, position: 'Forward' },
{ name: 'Rivaldo', points: 20, position: 'Forward/Midfielder' },
{ name: 'Roberto Carlos', points: 20, position: 'Defender' },
{ name: 'David Beckham', points: 20, position: 'Midfielder/Winger' },
{ name: 'Bobby Charlton', points: 20, position: 'Midfielder/Forward' },
{ name: 'Luis Figo', points: 20, position: 'Midfielder/Winger' },
{ name: 'Franco Baresi', points: 20, position: 'Defender' },
{ name: 'George Weah', points: 20, position: 'Forward' },
{ name: 'Samuel Eto\'o', points: 20, position: 'Forward' },
{ name: 'Alessandro Del Piero', points: 20, position: 'Forward' },
{ name: 'Didier Drogba', points: 20, position: 'Forward' },
{ name: 'Ryan Giggs', points: 15, position: 'Midfielder/Winger' },
{ name: 'Gianluigi Buffon', points: 15, position: 'Goalkeeper' },
{ name: 'Eric Cantona', points: 15, position: 'Forward' },
{ name: 'Steven Gerrard', points: 15, position: 'Midfielder' },
{ name: 'Frank Lampard', points: 15, position: 'Midfielder' },
{ name: 'Fabio Cannavaro', points: 15, position: 'Defender' },
{ name: 'Michael Laudrup', points: 15, position: 'Midfielder/Forward' },
{ name: 'Hristo Stoichkov', points: 15, position: 'Forward' },
{ name: 'Dennis Bergkamp', points: 15, position: 'Forward' },
{ name: 'Clarence Seedorf', points: 15, position: 'Midfielder' },
{ name: 'Patrick Vieira', points: 10, position: 'Midfielder' },
{ name: 'Raúl González', points: 10, position: 'Forward' },
{ name: 'Francesco Totti', points: 10, position: 'Forward' },
{ name: 'Pavel Nedvěd', points: 10, position: 'Midfielder' },
{ name: 'Cafu', points: 10, position: 'Defender' },
{ name: 'Kaká', points: 10, position: 'Midfielder' },
{ name: 'Xabi Alonso', points: 10, position: 'Midfielder' },
{ name: 'Zlatan Ibrahimović', points: 10, position: 'Forward' },
{ name: 'Philipp Lahm', points: 10, position: 'Defender' },
{ name: 'Paul Scholes', points: 10, position: 'Midfielder' },
{ name: 'Michael Ballack', points: 10, position: 'Midfielder' },
{ name: 'Arjen Robben', points: 10, position: 'Forward/Winger' },
{ name: 'Franck Ribéry', points: 10, position: 'Forward/Winger' },
{ name: 'Gary Lineker', points: 10, position: 'Forward' },
{ name: 'Alan Shearer', points: 10, position: 'Forward' },
{ name: 'Nemanja Vidić', points: 10, position: 'Defender' },
{ name: 'Lilian Thuram', points: 10, position: 'Defender' },
{ name: 'Roberto Rivelino', points: 10, position: 'Midfielder' },
{ name: 'Fernando Torres', points: 10, position: 'Forward' },
{ name: 'Mario Kempes', points: 10, position: 'Forward' },
{ name: 'Jean-Pierre Papin', points: 10, position: 'Forward' },
{ name: 'Deco', points: 10, position: 'Midfielder' },
{ name: 'Marco Tardelli', points: 10, position: 'Midfielder' },
{ name: 'Karl-Heinz Rummenigge', points: 10, position: 'Forward' },
{ name: 'Gheorghe Hagi', points: 10, position: 'Midfielder' },
{ name: 'Jairzinho', points: 10, position: 'Forward/Winger' },
{ name: 'Gaetano Scirea', points: 10, position: 'Defender' },
{ name: 'Daniel Passarella', points: 10, position: 'Defender' },
{ name: 'Ruud van Nistelrooy', points: 10, position: 'Forward' },
{ name: 'Robert Lewandowski', points: 10, position: 'Forward' },
{ name: 'Patrick Kluivert', points: 10, position: 'Forward' },
{ name: 'Gianluca Zambrotta', points: 10, position: 'Defender' },
{ name: 'Wesley Sneijder', points: 10, position: 'Midfielder' },
{ name: 'Diego Forlán', points: 10, position: 'Forward' },
{ name: 'Ángel Di María', points: 10, position: 'Midfielder/Winger' },
{ name: 'Pierre-Emerick Aubameyang', points: 10, position: 'Forward' },
{ name: 'Alexis Sánchez', points: 10, position: 'Forward/Winger' },
{ name: 'Edinson Cavani', points: 10, position: 'Forward' },
{ name: 'Sadio Mané', points: 10, position: 'Forward/Winger' },
{ name: 'Mohamed Salah', points: 10, position: 'Forward/Winger' },
{ name: 'Luka Modrić', points: 10, position: 'Midfielder' },
{ name: 'Sergio Ramos', points: 10, position: 'Defender' },
{ name: 'Marcelo', points: 10, position: 'Defender' },
{ name: 'Roberto Firmino', points: 10, position: 'Forward' },
{ name: 'Virgil van Dijk', points: 10, position: 'Defender' },
{ name: 'Antoine Griezmann', points: 10, position: 'Forward' },
{ name: 'David Villa', points: 10, position: 'Forward' },
{ name: 'James Rodríguez', points: 10, position: 'Midfielder' },
{ name: 'Karim Benzema', points: 10, position: 'Forward' },
{ name: 'Paul Pogba', points: 10, position: 'Midfielder' },
{ name: 'Kevin De Bruyne', points: 5, position: 'Midfielder' },
{ name: 'N’Golo Kanté', points: 5, position: 'Midfielder' },
{ name: 'Bernardo Silva', points: 5, position: 'Midfielder' },
{ name: 'Arturo Vidal', points: 5, position: 'Midfielder' },
{ name: 'Ivan Rakitić', points: 5, position: 'Midfielder' },
{ name: 'Jorginho', points: 5, position: 'Midfielder' },
{ name: 'Radja Nainggolan', points: 5, position: 'Midfielder' },
{ name: 'Thiago Alcântara', points: 5, position: 'Midfielder' },
{ name: 'Marco Verratti', points: 5, position: 'Midfielder' },
{ name: 'Christian Eriksen', points: 5, position: 'Midfielder' },
{ name: 'Wayne Rooney', points: 5, position: 'Forward' },
{ name: 'Kylian Mbappé', points: 5, position: 'Forward' },
{ name: 'Neymar', points: 5, position: 'Forward/Winger' },
{ name: 'Erling Haaland', points: 5, position: 'Forward' },
{ name: 'Romelu Lukaku', points: 5, position: 'Forward' },
{ name: 'Harry Kane', points: 5, position: 'Forward' },
{ name: 'Gonzalo Higuaín', points: 5, position: 'Forward' },
{ name: 'Roberto Firmino', points: 5, position: 'Forward' },
{ name: 'David Trezeguet', points: 5, position: 'Forward' },
{ name: 'Michael Owen', points: 5, position: 'Forward' },
{ name: 'Mats Hummels', points: 5, position: 'Defender' },
{ name: 'Thiago Silva', points: 5, position: 'Defender' },
{ name: 'Des Walker', points: 5, position: 'Defender' },
{ name: 'Héctor Chumpitaz', points: 5, position: 'Defender' },
{ name: 'Diego Godín', points: 5, position: 'Defender' },
{ name: 'Petr Čech', points: 5, position: 'Goalkeeper' },
{ name: 'Oliver Kahn', points: 5, position: 'Goalkeeper' },
{ name: 'Alisson Becker', points: 5, position: 'Goalkeeper' },
{ name: 'Jan Oblak', points: 5, position: 'Goalkeeper' },
{ name: 'Thibaut Courtois', points: 5, position: 'Goalkeeper' },
{ name: 'Sepp Maier', points: 5, position: 'Goalkeeper' },
{ name: 'Gordon Banks', points: 5, position: 'Goalkeeper' },
{ name: 'Vincent Kompany', points: 5, position: 'Defender' },
{ name: 'Ashley Cole', points: 5, position: 'Defender' },
{ name: 'Rio Ferdinand', points: 5, position: 'Defender' },
{ name: 'John Terry', points: 5, position: 'Defender' },
{ name: 'Roberto Ayala', points: 5, position: 'Defender' },
{ name: 'Laurent Blanc', points: 5, position: 'Defender' },
{ name: 'Jaap Stam', points: 5, position: 'Defender' },
{ name: 'Raphael Varane', points: 5, position: 'Defender' },
{ name: 'Antonio Cabrini', points: 5, position: 'Defender' },
{ name: 'Zeki Çelik', points: 5, position: 'Defender' },
{ name: 'Arda Güler', points: 5, position: 'Midfielder' },
{ name: 'Orkun Kökçü', points: 5, position: 'Midfielder' },
{ name: 'İrfan Can Kahveci', points: 5, position: 'Midfielder' },
{ name: 'Enes Ünal', points: 5, position: 'Forward' },
{ name: 'Yusuf Yazıcı', points: 5, position: 'Midfielder' },
{ name: 'Abdülkadir Ömür', points: 5, position: 'Midfielder' },
{ name: 'Ozan Kabak', points: 5, position: 'Defender' },
{ name: 'Kerem Aktürkoğlu', points: 5, position: 'Forward/Winger' },
{ name: 'Uğurcan Çakır', points: 5, position: 'Goalkeeper' },
{ name: 'ASIM OZBILICI', points: 50, position: 'Forward' }, // New player
{ name: 'KEREM OZBILICI', points: 50, position: 'Forward' }, // New player
{ name: 'OMER OZBILICI', points: 50, position: 'Forward' },  // New player
];
